Remove leading | if note_id_func returns '' or nil
epwalsh/obsidian.nvim pull request #160
Opened 2023-07-24 05:07 UTC by NachoxMacho

Resolves #159
Adjusts `cmp_obsidian_new` so that if the `note_id_func` function returns an empty string or nil, there is no longer a leading `|`. 
I've confirmed on my end that this works with the following config:
```lua
    note_id_func = function (_)
        return ''
    end
```
![image](https://github.com/epwalsh/obsidian.nvim/assets/10048014/889caff8-03d9-4ad9-9dab-c4423a435969)

I believe I've updated all relevant documentation and changelogs in accordance with the contributing guidelines.

2023-07-24 17:03 UTC, epwalsh requested changes
Hey @NachoxMacho, I'm nervous about allowing `note_id_func` to return an empty string or nil because that departs from the original API and might have unintended consequences elsewhere. Alternatively I'd prefer adding another configuration option to turn this behavior on.

2023-07-24 17:12 UTC, NachoxMacho commented
I understand there could be unintended consequences of this change, I have only tested it briefly to my use cases. So something like a new top level boolean config option like `prepend_note_id` would be more desired here? If that's false then the code previously modified would just not prepend the `note_id_func` output, and it defaults to true? Is that more along what you had in mind to accomplish this?

2023-07-24 17:20 UTC, epwalsh commented
Yes that sounds great. Except instead of a top-level config option, let's make it part of the `completion` section. Sound good?

2023-07-24 18:52 UTC, NachoxMacho commented
Sounds good to me, I'll make the adjustments to this PR later today

2023-07-24 22:51 UTC, NachoxMacho commented
@epwalsh I've updated the code accordingly and validated on my system that toggling the flag adds the listed effect. The default for the new field is `true`so it doesn't break current configurations.

2023-07-25 03:00 UTC, epwalsh commented on README.md
> +    -- Whether to add the output of the node_id_func to new notes in autocompletion
```suggestion
    -- Whether to add the output of the node_id_func to new notes in autocompletion.
    -- E.g. "[[Foo" completes to "[[foo|Foo]]" assuming "foo" is the ID of the note.
```

2023-07-25 03:00 UTC, epwalsh approved these changes
LGTM! Thanks @NachoxMacho

2023-07-25 03:01 UTC, merged