Provide custom format for dailynotes file name
epwalsh/obsidian.nvim pull request #49
Opened 2022-11-13 20:33 UTC by AntoineBalaine

Hello, 

I created an option to provide a custom date format to daily notes, in the config. 

I love every bit of obsidian.nvim but found that I had been using a different file format, so here it is. 
 
If you like this option, let me know and I can add a small mention in the readme. 

Cheers!

2022-11-15 23:54 UTC, epwalsh commented
Hey @AntoineBalaine, this is great, thank you! Please add to the README

2022-11-18 02:48 UTC, AntoineBalaine commented
@epwalsh Et voilà!

2022-11-23 16:19 UTC, epwalsh reviewed
Sorry for the slow responses..

I think we should call this field `format_date` instead of `date_format` since it's a function. What do you think?

2022-11-23 16:19 UTC, epwalsh commented on lua/obsidian/config.lua
> +---@field date_format string|osdate
```suggestion
---@field format_date function|?
```

2022-11-23 16:19 UTC, epwalsh commented on README.md
> +You can customize the file name of your daily notes by providing a date format:
```suggestion
You can customize the file name of your daily notes by providing a date formatting function:
```

2022-11-23 16:19 UTC, epwalsh commented on README.md
> +    date_format = function()
```suggestion
    format_date = function()
```

2022-11-23 16:19 UTC, epwalsh commented on lua/obsidian/config.lua
> +    date_format = nil,
```suggestion
    format_date = nil,
```

2022-11-23 16:19 UTC, epwalsh commented on lua/obsidian/init.lua
> +  local id = date_format
```suggestion
  local formatted_date
  if self.opts.daily_notes.format_date ~= nil then
    formatted_date = self.opts.daily_notes.format_date()
  else
    formatted_date = os.date("%Y-%m-%d")
  end
  local id = format_date
```

2023-03-31 22:58 UTC, AntoineBalaine commented
> Hi, can I continue this PR?

Of course!

2023-05-21 13:33 UTC, evtuhovich commented
:+1:

I've monkey patched this for myself, so waiting for this PR

2023-05-23 03:52 UTC, AntoineBalaine commented
> +1
> 
> I've monkey patched this for myself, so waiting for this PR

Here's the update.

2023-05-23 23:08 UTC, epwalsh requested changes
Thanks @AntoineBalaine, just one comment

2023-05-23 23:08 UTC, epwalsh commented on lua/obsidian/init.lua
> +    formatted_date = self.opts.daily_notes.format_date()
We'll need to use this below in `client.yesterday` as well. So the `format_date()` function should probably take an optional `time` argument just like `os.date()`.

2023-05-30 18:14 UTC, epwalsh commented
Let's go with #138 instead. It keeps things simpler and handles the "yesterday" case as well.

2023-05-30 18:14 UTC, closed without merging